## Assignment 2 submission
__Name:__  Duong Doan Tung

__Student number:__  21010294

__Programming language used:__  Python

__Programming environment used:__  Jupyter Notebook

---

## Part 1

2.4 Compute the following products:

In [2]:
import numpy as np
#b
A = np.arange(1, 10).reshape(3, 3)
B = np.array([
    [1,1,0],
    [0,1,1],
    [1,0,1]
])
ans = np.dot(A, B)
print(ans)

#d
A = np.array([
    [1,2,1,2],
    [4,1,-4,-1],
])
B = np.array([
    [0,3],
    [1,-1],
    [2,1],
    [5,2]
])
ans = np.dot(A, B)
print(ans)


[[ 4  3  5]
 [10  9 11]
 [16 15 17]]
[[ 14   6]
 [-12   5]]


2.5b Find the set S of all solutions in x of the following inhomogeneous linear system Ax = b, where A and b are defined as follows:

In [5]:
import numpy.linalg as la
import scipy.linalg as spla
A = np.array([
    [1,-1,0,0,1],
    [1,1,0,-3,0],
    [2,-1,0,1,-1],
    [-1,2,0,-2,-1]
])
#remove the 3rd column
A = np.delete(A, 2, 1)
B = np.array([3,6,5,-1]).reshape(4,1)

X = np.dot(la.inv(A), B)
print(X)

[[4.]
 [0.]
 [4.]
 [0.]]


2.11 Write 
```python
y = [[1],
     [-2],
     [5]]
```
as a linear combination of the vectors 
```python
x1 = [[1],
      [1],
      [1]]
x2 = [[1],
      [2],
      [3]]
x3 = [[2],
      [-1],
      [1]]
```


In [12]:
x1 = np.array([[1],
      [1],
      [1]])
x2 = np.array([[1],
      [2],
      [3]])
x3 = np.array([[2],
      [-1],
      [1]])

#y is linear combination of x1, x2, x3
y = np.array([[1],[-2],[5]])

#solve for alpha1, alpha2, alpha3
X = np.hstack((x1, x2, x3))
A = np.dot(la.inv(X), y)
print(A.T)


[[-6.  3.  2.]]


Or in the mathematical form:
-6x1 + 3x2 + 2x3 = y

3.3 Compute the distance between x,y

In [15]:
X = np.array([[1],
        [2],
        [3]])
Y = np.array([[-1],
        [-1],
        [0]])

#distance between X and Y using inner product (a)
dist = np.dot(X.T, Y)
print(dist[0,0])
#(b)
A = np.array([[2,1,0],
              [1,3,-1],
              [0,-1,2]])
dist = np.dot(np.dot(X.T, A), Y)
print(dist[0,0])

-3
-8


4.2 Compute the following determinants efficiently:

In [16]:

A = np.array([  [2,0,1,2,0],
                [2,-1,0,1,1],
                [0,1,2,1,2],
                [-2,0,2,-1,2],
                [2,0,0,1,1]
            ])
#deteminant of A
det = la.det(A)
print(det)

6.000000000000003


4.4 Comute all eigenspaces of the following matrix:

In [17]:

A = np.array([  [0,-1,1,1],
                [-1,1,-2,3],
                [2,-1,0,0],
                [1,-1,1,0]
            ])
#eigenspace of A
eig = la.eig(A)
print(eig)


(array([ 2.        ,  1.        , -1.00000002, -0.99999998]), array([[ 5.77350269e-01,  5.00000000e-01,  1.58709825e-08,
         1.58709821e-08],
       [-1.44897623e-16,  5.00000000e-01, -7.07106773e-01,
         7.07106789e-01],
       [ 5.77350269e-01,  5.00000000e-01, -7.07106789e-01,
         7.07106773e-01],
       [ 5.77350269e-01,  5.00000000e-01,  3.20493788e-17,
        -6.19518495e-17]]))


4.7d Are the following matrices diagonalizable? If yes, determine their diagonal
form and a basis with respect to which the transformation matrices are diagonal. If no, give reasons why they are not diagonalizable

In [21]:
'''
A = 

5 −6 −6
−1 4 2
3 −6 −4
'''
A = np.array([  [5,-6,-6],
                [-1,4,2],
                [3,-6,-4]
            ])
#check if A diagonalizable or not
iA = la.inv(A)
eig = la.eig(A)

if np.allclose(np.dot(iA, A), np.diag(eig[0])):
    print('A is diagonalizable')
else:
    print('A is not diagonalizable')




A is not diagonalizable


4.9 Find the singular value decomposition

In [22]:
A = np.array([  [2,2],
                [-1,1]])
#find the singular value decomposition of A
U, s, V = la.svd(A)
print(U)
print(s)
print(V)

[[-1.00000000e+00  1.11022302e-16]
 [ 8.64164897e-17  1.00000000e+00]]
[2.82842712 1.41421356]
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]


## Part 2
A

In [5]:

import numpy as np
#Use arange to create a variable named foo that stores an array of numbers from 0 to 29, inclusive. Print foo and its shape.
foo = np.arange(30)
print(foo)
print(foo.shape)




[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27
 28 29]
(26,)


B

In [2]:
#Use the reshape function to change foo to a validly-shaped two-dimensional matrix and store it in a new variable called bar. Print bar and its shape.
bar = foo.reshape(6,5)
print(bar)
print(bar.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
(6, 5)


C

In [4]:
baz = foo.reshape(2,3,5)
print(baz)
print(baz.shape)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


D

In [13]:
#D
print(bar)

#change first value row 2 to -1
bar[1,0] = -1
print(bar)

print(np.sum(bar, axis=1, keepdims=True))

[[ 0  1  2  3  4]
 [-1  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
[[ 0  1  2  3  4]
 [-1  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
[[ 10]
 [ 29]
 [ 60]
 [ 85]
 [110]
 [135]]


E

In [15]:
print(baz)
#Sum baz over its second dimension and print the result.
print(baz.sum(axis=1))
#Sum baz over its third dimension and print the result.
print(baz.sum(axis=2))

print(baz.sum(axis=0))
#Sum baz over both its first and third dimensions and print the result.
print(baz.sum(axis=(0,2)))

[[[ 0  1  2  3  4]
  [-1  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
[[ 9 18 21 24 27]
 [60 63 66 69 72]]
[[ 10  29  60]
 [ 85 110 135]]
[[15 17 19 21 23]
 [19 27 29 31 33]
 [35 37 39 41 43]]
[ 95 139 195]


F

In [18]:
#F
print(bar)
#Slice out the second row of bar and print it.
print(bar[1,:])
#Slice out the last column of bar using the -1 notation and print it.
print(bar[:,-1])
#Slice out the top right 2 × 2 submatrix of bar and print it
print(bar[:2,3:])




[[ 0  1  2  3  4]
 [-1  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
[-1  6  7  8  9]
[ 4  9 14 19 24 29]
[[3 4]
 [8 9]]


## Part 3
A