## Part 2
#### A

In [5]:

import numpy as np
#Use arange to create a variable named foo that stores an array of numbers from 0 to 29, inclusive. Print foo and its shape.
foo = np.arange(30)
print(foo)
print(foo.shape)




[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27
 28 29]
(26,)


B

In [2]:
#Use the reshape function to change foo to a validly-shaped two-dimensional matrix and store it in a new variable called bar. Print bar and its shape.
bar = foo.reshape(6,5)
print(bar)
print(bar.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
(6, 5)


In [4]:
baz = foo.reshape(2,3,5)
print(baz)
print(baz.shape)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [13]:
#D
print(bar)

#change first value row 2 to -1
bar[1,0] = -1
print(bar)

print(np.sum(bar, axis=1, keepdims=True))

[[ 0  1  2  3  4]
 [-1  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
[[ 0  1  2  3  4]
 [-1  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
[[ 10]
 [ 29]
 [ 60]
 [ 85]
 [110]
 [135]]


In [15]:
print(baz)
#Sum baz over its second dimension and print the result.
print(baz.sum(axis=1))
#Sum baz over its third dimension and print the result.
print(baz.sum(axis=2))

print(baz.sum(axis=0))
#Sum baz over both its first and third dimensions and print the result.
print(baz.sum(axis=(0,2)))

[[[ 0  1  2  3  4]
  [-1  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
[[ 9 18 21 24 27]
 [60 63 66 69 72]]
[[ 10  29  60]
 [ 85 110 135]]
[[15 17 19 21 23]
 [19 27 29 31 33]
 [35 37 39 41 43]]
[ 95 139 195]


In [18]:
#F
print(bar)
#Slice out the second row of bar and print it.
print(bar[1,:])
#Slice out the last column of bar using the -1 notation and print it.
print(bar[:,-1])
#Slice out the top right 2 × 2 submatrix of bar and print it
print(bar[:2,3:])




[[ 0  1  2  3  4]
 [-1  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
[-1  6  7  8  9]
[ 4  9 14 19 24 29]
[[3 4]
 [8 9]]
